server:
  port: ${PORT:8080}
  tomcat:
    accesslog:
      enabled: false
    basedir: logs

spring:
  application:
    name: dansmultipro-test
  task:
    scheduling:
      pool:
        size: 10
  profiles:
    active: default
  servlet:
    multipart:
      max-file-size: 1GB
      max-request-size: 1GB
  datasource:
    url: jdbc:mysql://localhost:3306/dansmultipro?zeroDateTimeBehavior=CONVERT_TO_NULL&serverTimezone=Asia/Jakarta&createDatabaseIfNotExist=true
    username: root
    hikari:
      maximum-pool-size: 10
      max-lifetime: 60000
    tomcat:
      test-while-idle: true
      test-on-borrow: true
      validation-query: SELECT 1
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
        format_sql: true
      org:
        hibernate:
          envers:
            audit_table_suffix: _audit
            revision_field_name: revision
            revision_type_field_name: revision_type
    show-sql: false

services:
  dansmultipro:
    url: http://dev3.dansmultipro.co.id
  dansmultipro-positions:
    url: /api/recruitment/positions.json
  dansmultipro-positions-detail:
    url: /api/recruitment/positions/{ID}